### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TannerFilip** [xephora/Threat-Remediation-Scripts#1]
I'm interested in using your WaveBrowser remediation script at my company, but I want to make sure I'm good on the legal/compliance side of things. Do you have a license that these scripts are under? 

Thanks!

**Comment by xephora** [comment]
Hello TannerFilip, there is no license.  My scripts are free to use.  They were created over-time as I came across them in my environment. I had planned to update two of my scripts. I will work on this as soon as I get home.  They should be updated by 9pm est tonight. Thank you for your interest in my scripts.

**Comment by xephora** [comment]
Updates have been made and ready to use.  We will continue to add more scripts over-time.  Have a great day.

**Comment by TannerFilip** [comment]
Thank you very much!
