### ISSUE TITLE
Wave Browser

### ISSUE THREAD

**Issue by chan-man** [xephora/Threat-Remediation-Scripts#10]
I used the "WaveBrowser-Remediation-Script-Win10-BrowserKill.ps1" script earlier and it seemed to have missed 2 things.

The first thing is the desktop icon. I noticed it was being synced with one drive though so not sure if there is a way to script delete inside of OneDrive.
![Screenshot 2024-09-17 122816](https://github.com/user-attachments/assets/10d3c516-175b-45f4-b2c7-1f61099f9922)

The second thing it missed was the Taskbar icon.
![Screenshot 2024-09-17 122854](https://github.com/user-attachments/assets/33b24a80-f44f-432e-a781-0e857dd045ce)

**Comment by xephora** [comment]
Hey @chan-man, it's likely that updates have been made to WaveBrowser again. I will need to review the software and update the script with the latest paths. Can you tell me what the version of WaveBrowser on the client was?

**Comment by chan-man** [comment]
I'm sorry I did not get the version before removing it.

**Comment by xephora** [comment]
No problem! I'll provide an update shortly.

**Comment by xephora** [comment]
Sorry for the long wait. It's been an extremely busy few days.

Regarding your request to remove a file from cloud storage, such as OneDrive or Google Drive, please note that cloud storages are currently off-limit as of now.  I may consider adding this feature in the future.  I apologize for the inconvenience.  Your name has been credited as usual.  If you’re satisfied with the update, please let me know so I can close the issue.

The following paths were added to the remediation script.
```
"C:\Users\{USERNAME}\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\WaveBrowser.lnk"
"HKEY_USERS\{SID}\Software\RegisteredApplications" "WaveBrowser.5QMLTPZDDJG2BQZHV26QUN4ZK4"
"HKEY_USERS\{SID}\Software\Classes\CLSID\{9CD78CBC-FD21-4FFF-B452-9D792A58B7C4}\LocalServer32"
"HKEY_USERS\{SID}_Classes\CLSID\{9CD78CBC-FD21-4FFF-B452-9D792A58B7C4}\LocalServer32"
"HKEY_USERS\{SID}\Software\Microsoft\Windows\CurrentVersion\App Paths\wavebrowser.exe"
"HKEY_USERS\{SID}\Software\Clients\StartMenuInternet\WaveBrowser.5QMLTPZDDJG2BQZHV26QUN4ZK4"
```

**Comment by chan-man** [comment]
No issue at all. I figured there was a chance it couldn't happen right now just wanted to make a note of it. I appreciate all the great scripts though. I'll make as done.
