### ISSUE TITLE
Clearbar-Remediation-Script - Additional Scheduled Task Found

### ISSUE THREAD

**Issue by mclaughcj** [xephora/Threat-Remediation-Scripts#12]
In my environment, I found one additional task that is created on over half of the systems (1.1.3.0 and 1.1.4.0).

ClearWeatherCheck

**Comment by xephora** [comment]
Hello @mclaughcj,

~~I'll look into this for you shortly.  Is this in reference to the ClearBar unwanted software?~~   Woops, nvm.  You clearly stated Clearbar in the title of the issue.  I'll look into this shortly.

**Comment by mclaughcj** [comment]
That’s correct On Dec 5, 2024, at 6:58 AM, Shawn ***@***.***> wrote:﻿
Hello @mclaughcj,
I'll look into this for you shortly.  Is this in reference to the ClearBar unwanted software?

**Comment by xephora** [comment]
The following entries have been added to the Clearbar remediation script. I have verified that the script successfully removed the entries from systems on my end.

```
Filesystem:
C:\windows\system32\tasks\ClearWeatherCheck

Registry Hive:
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\TREE\ClearWeatherCheck
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Tracing\ClearBar_RASAPI32
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Tracing\ClearBar_RASMANCS
```

**Comment by xephora** [comment]
The script has been updated and your name has been credited!  Thank you for your assistance @mclaughcj.
