### ISSUE TITLE
Clearbar-Remediation-Script - Additional HKU\Software Keys

### ISSUE THREAD

**Issue by mclaughcj** [xephora/Threat-Remediation-Scripts#13]
In my environment, I found one additional subkeys of the HKU\<sid>\Software on systems with Clear 1.0.5.6 - 1.1.4.0.

HKU\$sid\Software\Clear
HKU\$sid\Software\Clear.app

**Comment by xephora** [comment]
Hello again @mclaughcj,

These entries already exist in the remediation script, and I have confirmed that they were successfully removed from the systems on my end.
