### ISSUE TITLE
Artifacts remaining

### ISSUE THREAD

**Issue by jendahl12** [xephora/Threat-Remediation-Scripts#2]
WaveBrowser script works well but we found that an artifact remains that can affect software inventory systems...and our ability to check off remediated systems.

Running the following script we can see that it still appears to be present on the system:

_$UserHives = Get-ChildItem Registry::HKEY_USERS\ |Where-Object {$_.Name -match '^HKEY_USERS\\S-1-5-21-[\d\-]+$'}
 
foreach($Hive in $UserHives)
{
    $Path = Join-Path $Hive.PSPath "Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
    $Path64 = Join-Path $Hive.PSPath "Software\Microsoft\Windows\CurrentVersion\Uninstall\*"
 
    Get-ItemProperty -Path $Path | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table -AutoSize
    Get-ItemProperty -Path $Path64 | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table -AutoSize
 
}_

**Comment by xephora** [comment]
Hello @jendahl12, I will look into this now.

**Comment by xephora** [comment]
Identified issue:

Added a check and removal.  Checked if both keys exist, if either key exist, then remove, otherwise no action required. Tested this on 3 devices and keys were removed.  I also added checks just incase removal fails, It will return an error letting you know which key exists.  Adding the updated code now.  Thank you for your report.

```powershell
$sid_list = Get-Item -Path "Registry::HKU\*" | Select-String -Pattern "S-\d-(?:\d+-){5,14}\d+"
foreach($j in $sid_list) {
	if ($j -notlike "*_Classes*") {
		$exists = Test-Path -Path "Registry::$j\Software\Microsoft\Windows\CurrentVersion\Uninstall\WaveBrowser" -ErrorAction SilentlyContinue
		$exists2 = Test-Path -Path "Registry::$j\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\WaveBrowser" -ErrorAction SilentlyContinue
		if ($exists -eq $True) {
            Remove-Item -Path "Registry::$j\Software\Microsoft\Windows\CurrentVersion\Uninstall\WaveBrowser" -Recurse -ErrorAction SilentlyContinue
            $exists = Test-Path -Path "Registry::$j\Software\Microsoft\Windows\CurrentVersion\Uninstall\WaveBrowser" -ErrorAction SilentlyContinue
            if ($exists -eq $True) {
            	"WaveBrowser Removal Unsuccessful => Registry::$j\Software\Microsoft\Windows\CurrentVersion\Uninstall\WaveBrowser"
            }
        }
        if ($exists2 -eq $True) {
            Remove-Item -Path "Registry::$j\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\WaveBrowser" -Recurse -ErrorAction SilentlyContinue
            $exists2 = Test-Path -Path "Registry::$j\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\WaveBrowser" -ErrorAction SilentlyContinue
            if ($exists2 -eq $True) {
                "WaveBrowser Removal Unsuccessful => Registry::$j\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\WaveBrowser"
            }
        }
    }
}
```

Results from logic testing:

```
runscript -Raw=```$sid_list = Get-Item -Path "Registry::HKU\*" | Select-String -Pattern "S-\d-(?:\d+-){5,14}\d+"
Found WaveBrowser.. Removing..
WaveBrowser has been removed..

runscript -Raw=```$sid_list = Get-Item -Path "Registry::HKU\*" | Select-String -Pattern "S-\d-(?:\d+-){5,14}\d+"
```

**Comment by xephora** [comment]
I updated all WaveBrowser scripts and added your name as credit to the WaveBrowser remediation page.  Thank you for reporting this and have a great day.

https://github.com/xephora/Threat-Remediation-Scripts/tree/main/WaveBrowser
