### ISSUE TITLE
No output on the OneLaunch script

### ISSUE THREAD

**Issue by mcrommert** [xephora/Threat-Remediation-Scripts#3]
I have been running the OneLaunch script and it seems to be doing what it says on the tin but i'm not getting any output when using in powershell on the computer or through crowdstrike rtr - the code looks right to me too so unsure why

**Comment by mcrommert** [comment]
To update of course as soon as i send this i get an output - running on two machines through crowdstrike it output "This script failed to remove C:\Users\xxxxxxxxxx\AppData\Local\OneLaunch"

**Comment by mcrommert** [comment]
Oh no i shouldn't have said anything 🤣

**Comment by xephora** [comment]
Haha, I noticed a huge influx of alerts on my end.  I removed the script for a short period, I'm working on updating the script and will re-release it shortly.  I'm going to do some heavy testing on my side before release.  Thank you for bringing this to my attention.

**Comment by mcrommert** [comment]
No problem - appreciate the help - I don't know if crowdstrike changed something or something went crazy

**Comment by xephora** [comment]
I'll also, leave an friendly update to the main page of my repository.

**Comment by xephora** [comment]
I contacted the engineers, they made changes which caused the detections.  This explains the influx.

**Comment by xephora** [comment]
@mcrommert

I've re-written the script and optimized it.  I've tested the script on a multiple devices without any issues.  Regarding the the lack of feedback from the script, the script is designed to check and remove files associated with OneLaunch.  I've added a check so that, if the script fails to remove the file, it will let you know.  If you do not see any feedback, it's a good thing!  Let me know if this works for you.

**Comment by xephora** [comment]
@mcrommert  I have also attributed the credit to your name. I look forward to hearing from you soon!

https://github.com/xephora/Threat-Remediation-Scripts/tree/main/OneLaunch

**Comment by mcrommert** [comment]
@xephora Thank you so much for all your work :)

I ran it over rtr on crowdstrike with all rights and i got this message "Timed out waiting for script to complete"

Looking at the appdata folder onelaunch is still there but all the main files seem to be gone - 
On second run 
Failed to remove OneLaunch -> C:\Users\xxxxx\appdata\local\OneLaunch

**Comment by mcrommert** [comment]
I learned something interesting - if i cd into the onelaunch folder in crowdstrike and then try to run the script - it can't get rid of the folder

Second run while not in the OneLaunch folder was successful

**Comment by xephora** [comment]
Sorry for catching this late.  By stepping into a folder that you are targeting to remove, you are essentially locking the folder.  You should start an RTR session, run the script and see if it works.  As for the timeouts, If you are still experiencing this issue, can you tell me what Operating System you are running the script on?  I have tested this one Windows 11 and 10.  Also, I have learned that some security agents behave differently when running custom scripts.

**Comment by xephora** [comment]
> I learned something interesting - if i cd into the onelaunch folder in crowdstrike and then try to run the script - it can't get rid of the folder
> 
> Second run while not in the OneLaunch folder was successful

Ohhh, I see now..  Well, I'm happy that worked for you!

**Comment by xephora** [comment]
If you believe this issue was resolved, I will mark it closed.

**Comment by mcrommert** [comment]
Yes its resolved - the only issue is crowdstrike related timeouts and it only happens part of the time - probably when its doing a lot of work

I'm running this on multiple versions of win 10 but mostly 22H2

**Comment by xephora** [comment]
I'm happy that its working for you.  CrowdStrike will sometimes timeout if the network connection is unable, if the device is in shutdown phase or if the device's performance is slow.

**Comment by mcrommert** [comment]
building this into a crowdstrike fusion workflow :)
