### ISSUE TITLE
Trying to upload OneLaunch script into Crowdstrike

### ISSUE THREAD

**Issue by aknights1** [xephora/Threat-Remediation-Scripts#5]
Hello there! I am trying to upload and implement the OneLaunch remediation script, but maybe I am missing something. Where do we upload it and are there any prerequisites? I uploaded it in the the response scripts and files section. Please advise, much thanks!

**Comment by xephora** [comment]
Hello @aknights1,

Thank you for reaching out. If you already have the necessary permissions, you can create a script in the 'Response scripts and files' section of your CrowdStrike platform. If you don't have these permissions, please contact your CrowdStrike administrator or Technician Account Manager for assistance.

Here's how to proceed once you have the required permissions:

1. Go to the CrowdStrike menu.
2. Select 'Host Setup and Management'.
3. Choose 'Response scripts and files'.
4. Click 'Create script' in the top right corner.
5. Enter your script content in the script window.
6. Name your script, set the Shell type to 'PowerShell', and decide whether to share it with others (e.g., users with the role of RTR administrator or RTR Active Responder). Note that sharing settings depend on your CrowdStrike administrator's policies.

To use your script with real-time response, connect to a host, open the right-side panel, click on 'Scripts', select 'Custom scripts', and then choose your script. The script is designed for easy execution. If you encounter issues, these might be related to the security agent on the host, a specific policy, or an outdated operating system. Enjoy!

**Comment by aknights1** [comment]
Thanks so much for your response and steps! I have the script created. To use it with real time response, is where I'm running into a few things. How do I connect to all of our hosts/workstations for detection and execution? If that's possible.

Thanks again!

**Comment by xephora** [comment]
The support I can offer is specific to the script.  However, your request seems to pertain to the CrowdStrike platform and its automation features.  For more information regarding your request, I recommend reaching out to your Technical Account Manager or opening a support case with CrowdStrike.

**Comment by aknights1** [comment]
Gotcha, I thought it can do some automation by default, or by picking an option within the interface. I will take your recommendation and reach out to our CrowdStrike contact. Thanks again for your assistance, expertise, and providing these helpful scripts.

**Comment by xephora** [comment]
Sure thing, have a great day!
