### ISSUE TITLE
OneDrive Shortcuts

### ISSUE THREAD

**Issue by zzLukozz** [xephora/Threat-Remediation-Scripts#6]
I am having an issue running this code with users that have a linked OneDrive. It will remove anything for OneDrive for business but not the Desktop for them or the Startmenu.

It deletes the app and then when you click on the app it asks if you want to delete the shortcut. Same for the Start Menu

![Screenshot 2024-07-22 162610](https://github.com/user-attachments/assets/68fcacaa-16af-4349-b023-9233c907c8c0)

**Comment by xephora** [comment]
Firstly, I’m sorry to hear about the issue you’re experiencing.  Just to confirm the problem, there are two shortcuts in the user's desktop and start menu which is not being properly removed, also you mentioned the user is linked to their OneDrive.  Does that sound correct?  Can you please share the two paths for the shortcuts and redact the username for security reasons?

**Comment by zzLukozz** [comment]
![image](https://github.com/user-attachments/assets/e92c3a13-80a0-4bcb-bf61-f84c743ed5f8)

Adding this to 
C:\Users\$user\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneLaunch

Target for the Desktop icon
C:\Users\$user\AppData\Local\OneLaunch\5.32.0\OneLaunch.exe /a=browser /startedFrom=desktopIcon
Start In
C:\Users\$user\AppData\Local\OneLaunch\5.32.0

there is a back slash between the Users and $User
$User is the current logged in user

Adding this deletes the start menu link
![image](https://github.com/user-attachments/assets/0c4d38cb-95b0-4312-96ed-445280c11f5f)

**Comment by xephora** [comment]
Ah, I see, good catch!  OneLaunch v5.25.0 appears to have added a OneLaunch directory in the startup menu, just as you said.  I'll add that path to the remediation script.  Thank you for reporting!

```
C:\users\{user}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneLaunch
C:\users\{user}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneLaunch\OneLaunch.lnk
```

**Comment by xephora** [comment]
I updated the remediation script to include the new path.  I tested the script from my end and confirmed the directory was removed successfully.  Please let me know if you are happy with the change 👍.

**Comment by zzLukozz** [comment]
"C:\Users\$user\OneDrive - company\Desktop\OneLaunch.lnk"

This will remove it from the desktop. take about a minute. If not just pause OneDrive and then Unpause and the sync with OneDrive will work correctly.

The "OneDrive -company" is whatever the user's Onedrive is. The command by default looks up OneDrive for business but not this other OneDrive

Thanks for the help and glad we got it all fixed up or at least until the next time.

**Comment by zzLukozz** [comment]
Thanks for the help!

**Comment by xephora** [comment]
I accidentally re-opened. Have a great day!
