### ISSUE TITLE
No Issue, just question. Newb IT person wants to introduce it to boss

### ISSUE THREAD

**Issue by CartmansPiehole** [xephora/Threat-Remediation-Scripts#7]
Excuse this newb question, but I would like to understand how these scripts work, how to implement them, what I would need prior to implement them.  I would need to explain it to my boss.

I'm interested in the NewWave Browser and OneLauncher scripts.  Out of everything listed, these are our two main problems.  We also have issues with OperaGX Browser, but I was thinking of trying to write a script based on one of yours, I'm not sure how effective this would be.

**Comment by xephora** [comment]
> Excuse this newb question, but I would like to understand how these scripts work, how to implement them, what I would need prior to implement them. I would need to explain it to my boss.
> 
> I'm interested in the NewWave Browser and OneLauncher scripts. Out of everything listed, these are our two main problems. We also have issues with OperaGX Browser, but I was thinking of trying to write a script based on one of yours, I'm not sure how effective this would be.

Hello!

Before diving into these scripts, you might want to review how your department manages system software. For instance, tools like Microsoft System Center Configuration Manager (SCCM) or Microsoft Intune can be used to remove software in bulk. However, if these tools are not available or suitable for your environment, you may need to consider alternative methods for software removal on a case-by-case basis.

These scripts are designed to be run from an Endpoint Detection & Response (EDR) platform called CrowdStrike (CS). With CrowdStrike, you can upload PowerShell or Bash scripts to a private CS Cloud repository linked to your tenant. You can then trigger these scripts manually when investigating a host or automate their use based on specific conditions. Additionally, a Security Orchestration, Automation, and Response (SOAR) platform can be used to automate bulk remediation.

While the scripts can be executed without CrowdStrike or any other specific tools, running them might be subject to company policies, which is beyond the scope of support.

If you're new to this, don't worry, everyone starts somewhere. It’s important to understand the code before running it. I recommend creating a few remediation scripts on your own and comparing them with the one I provided. This practice will help you appreciate the time and effort involved and better understand the objectives.

Regarding OneLaunch and WaveBrowser, the PowerShell scripts are highly effective at removing these applications. I use these scripts frequently myself.

I hope this information is helpful. Wishing you the best, and have a great day!
