### ISSUE TITLE
OneLauncher Script - Tested on Hyper-V VM

### ISSUE THREAD

**Issue by CartmansPiehole** [xephora/Threat-Remediation-Scripts#8]
I tested your OneLaunch script on a Hyper-V VM, simply by copying and pasting into Administrative Powershell.  I realize this might not be the intended usage of the script, but I just wanted to test it.

The end result was that it looks like it removed OneLaunch, however I noticed it left a few things in the registry.  I'm not sure if this was left intentionally or if this has to do with the fact that it's a Hyper-V VM.  Note that the Domain User's SID is **S-1-5-21-3962865489-3230109862-1382926240-2104**.  Again, it's a test environment, not production, so I have no issues posting this info.

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Tracing\onelaunch_RASMANCS
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Tracing\onelaunch_RASAPI32
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{31B2B846-FC8D-4BB1-8566-8572875ED3F7}
Path: \OneLaunchLaunchTask
URI: \OneLaunchLaunchTask
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\OneLaunchLaunchTask

Computer\HKEY_USERS\S-1-5-21-3962865489-3230109862-1382926240-2104\SOFTWARE\Microsoft\Windows\CurrentVersion\ApplicationAssociationToasts
OneLaunchHTML_.pdf: 0

Computer\HKEY_USERS\S-1-5-21-3962865489-3230109862-1382926240-2104\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppBadgeUpdated
OneLaunch: 3

Computer\HKEY_USERS\S-1-5-21-3962865489-3230109862-1382926240-2104\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
OneLaunchUpdater: C:\Users\LibPubJr\AppData\Local\OneLaunch\5.32.1\onelaunch.exeUpdaterProxy

HKEY_USERS\S-1-5-21-3962865489-3230109862-1382926240-2104\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC
C:\Users\LibPubJr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneLaunch\OneLaunch.lnk
C:\Users\LibPubJr\AppData\Local\OneLaunch\5.32.1\OneLaunch.exe
/a=browser

HKEY_USERS\S-1-5-21-3962865489-3230109862-1382926240-2104\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store
C:\Users\LibPubJr\Downloads\Onelaunch Software.exe

HKEY_USERS\S-1-5-21-3962865489-3230109862-1382926240-2104\SOFTWARE\RegisteredApplications
OneLaunch
```

**Comment by xephora** [comment]
Hello again! I’m currently reviewing this. Thank you for providing the entries.

**Comment by xephora** [comment]
Hello,

Sorry for the delayed response. Based on the latest version of OneLaunch (5.32.1) and your feedback, I have added the following keys to the remediation script. Please note that some keys were either already included in the script or did not exist.

The following keys are added to the remediation script.

- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Tracing\onelaunch_RASMANCS
- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Tracing\onelaunch_RASAPI32
- HKU\SID\SOFTWARE\Microsoft\Windows\CurrentVersion\ApplicationAssociationToasts.OneLaunchHTML_.pdf
- HKU\SID\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppBadgeUpdated.OneLaunch
- HKU\SID\SOFTWARE\RegisteredApplications.OneLaunch
- HKU\SID\SOFTWARE\Microsoft\Windows\CurrentVersion\Run.OneLaunchUpdater
- HKU\SID\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC.{n} (Conditional removal)

The following key or value did not exist, please confirm the version of OneLaunch you tested.

- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{31B2B846-FC8D-4BB1-8566-8572875ED3F7}
- HKEY_USERS\SID\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store

The following key was already in the remediation script and was tested working.

- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\OneLaunchLaunchTask

Thank you for reporting this issue. If you are satisfied with the change, I will proceed to close the thread.
