### ISSUE TITLE
One Launch

### ISSUE THREAD

**Issue by chan-man** [xephora/Threat-Remediation-Scripts#9]
The one launch script misses deleting the following directory:
C:\users\"UserProfile"\AppData\Roaming\Microsoft\Start Menu\Programs\OneLaunch

![Screenshot 2024-09-11 121846](https://github.com/user-attachments/assets/292c243e-0181-40ed-bdf7-347670e26373)

**Comment by xephora** [comment]
Hello @chan-man, thanks for reaching out.  I will work on this as soon as possible!

**Comment by xephora** [comment]
Hello @chan-man, Sorry for the delayed response.   I’ve added the path to the remediation script, tested and confirmed that the directory has been removed.  Thank you for highlighting this issue!  Please let me know if this update helps.

**Comment by chan-man** [comment]
Will do and thanks for the quick update!

**Comment by xephora** [comment]
Absolutely!
